# Generated by Django 4.2.30 on 2026-05-11 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admision', '0002_alter_citaciondonante_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('servicio', models.CharField(max_length=120)),
                ('diagnostico', models.TextField()),
                ('ate_trans_alerg', models.BooleanField(default=False)),
                ('grupo_cabecera_h', models.CharField(max_length=20)),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('fraccionado', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('hemocomponente', models.ForeignKey(db_column='nro_bolsa', on_delete=django.db.models.deletion.PROTECT, related_name='transfusiones', to='inventario.hemocomponente')),
                ('paciente', models.ForeignKey(db_column='ci_paciente', on_delete=django.db.models.deletion.PROTECT, related_name='transfusiones', to='admision.paciente')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='transfusiones_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfusion',
                'verbose_name_plural': 'Transfusiones',
                'ordering': ['-hora_inicio', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('transfusion', models.ForeignKey(db_column='id_transfusion', on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='laboratorio.transfusion')),
            ],
            options={
                'verbose_name': 'Reaccion',
                'verbose_name_plural': 'Reacciones',
                'ordering': ['-fecha_hora', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PruebasPretransfHema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateTimeField()),
                ('salina', models.CharField(max_length=100)),
                ('albumina', models.CharField(max_length=100)),
                ('liss', models.CharField(max_length=100)),
                ('coombs', models.CharField(max_length=100)),
                ('cruzada_mayor', models.CharField(max_length=100)),
                ('cruzada_menor', models.CharField(max_length=100)),
                ('hemolisis', models.CharField(max_length=100)),
                ('anti_a', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo'), ('NO_REALIZADO', 'No realizado')], max_length=20)),
                ('anti_b', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo'), ('NO_REALIZADO', 'No realizado')], max_length=20)),
                ('anti_ab', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo'), ('NO_REALIZADO', 'No realizado')], max_length=20)),
                ('anti_d', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo'), ('NO_REALIZADO', 'No realizado')], max_length=20)),
                ('celula_a', models.CharField(max_length=100)),
                ('celula_b', models.CharField(max_length=100)),
                ('celula_o', models.CharField(max_length=100)),
                ('fenotipo', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('hemocomponente', models.ForeignKey(db_column='nro_bolsa', on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_pretransf_hema', to='inventario.hemocomponente')),
                ('solicitud', models.ForeignKey(db_column='nro_solicitud', on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_pretransf_hema', to='admision.solicitudtransfusion')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_pretransf_hema', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prueba pretransfusional hema',
                'verbose_name_plural': 'Pruebas pretransfusionales hema',
                'ordering': ['-fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PruebaPretransfusionalPAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_hora', models.DateTimeField()),
                ('anti_a', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo'), ('NO_REALIZADO', 'No realizado')], max_length=20)),
                ('anti_b', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo'), ('NO_REALIZADO', 'No realizado')], max_length=20)),
                ('anti_ab', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo'), ('NO_REALIZADO', 'No realizado')], max_length=20)),
                ('anti_d', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo'), ('NO_REALIZADO', 'No realizado')], max_length=20)),
                ('control_rhesus', models.CharField(max_length=100)),
                ('alfa', models.CharField(max_length=100)),
                ('beta', models.CharField(max_length=100)),
                ('o', models.CharField(max_length=100)),
                ('fenotipo', models.CharField(max_length=100)),
                ('hto', models.FloatField()),
                ('hb', models.FloatField()),
                ('coombs_directo', models.CharField(max_length=100)),
                ('resultado', models.CharField(choices=[('APTO', 'Apto'), ('NO_APTO', 'No apto'), ('PENDIENTE', 'Pendiente')], max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(db_column='paciente_id', on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_pretransfusionales_pac', to='admision.paciente')),
                ('solicitud', models.ForeignKey(db_column='nro_solicitud', on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_pretransfusionales_pac', to='admision.solicitudtransfusion')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_pretransfusionales_pac', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prueba pretransfusional PAC',
                'verbose_name_plural': 'Pruebas pretransfusionales PAC',
                'ordering': ['-fecha_hora', 'id'],
            },
        ),
    ]
