# Generated by Django 4.2.30 on 2026-05-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruebapretransfusionalpac',
            name='resultado',
            field=models.CharField(max_length=100),
        ),
    ]
