# Generated by Django 4.2.30 on 2026-05-19 22:45

from django.db import migrations, models


POSITIVE_VALUES = {"POSITIVO", "POSITIVA", "POSITIVE", "POS", "REACTIVO", "COMPATIBLE", "VALIDO", "VÁLIDO", "SI", "SÍ", "YES"}
BLOOD_GROUP_MAP = {
    "A RH+": "A+",
    "A+": "A+",
    "A RH-": "A-",
    "A-": "A-",
    "B RH+": "B+",
    "B+": "B+",
    "B RH-": "B-",
    "B-": "B-",
    "AB RH+": "AB+",
    "AB+": "AB+",
    "AB RH-": "AB-",
    "AB-": "AB-",
    "O RH+": "O+",
    "O+": "O+",
    "O RH-": "O-",
    "O-": "O-",
}


def normalize_positive_negative(value):
    normalized = str(value or "").strip().upper()
    return "POSITIVO" if normalized in POSITIVE_VALUES else "NEGATIVO"


def normalize_laboratory_choices(apps, schema_editor):
    PruebaPretransfusionalPAC = apps.get_model("laboratorio", "PruebaPretransfusionalPAC")
    PruebasPretransfHema = apps.get_model("laboratorio", "PruebasPretransfHema")

    pac_fields = ("control_rhesus", "alfa", "beta", "o", "coombs_directo")
    for prueba in PruebaPretransfusionalPAC.objects.all():
        for field in pac_fields:
            setattr(prueba, field, normalize_positive_negative(getattr(prueba, field)))
        prueba.fenotipo = BLOOD_GROUP_MAP.get(str(prueba.fenotipo or "").strip().upper(), "O+")
        prueba.save(update_fields=[*pac_fields, "fenotipo"])

    hema_fields = (
        "salina",
        "albumina",
        "liss",
        "coombs",
        "cruzada_mayor",
        "cruzada_menor",
        "hemolisis",
        "celula_a",
        "celula_b",
        "celula_o",
    )
    for prueba in PruebasPretransfHema.objects.all():
        for field in hema_fields:
            setattr(prueba, field, normalize_positive_negative(getattr(prueba, field)))
        prueba.fenotipo = BLOOD_GROUP_MAP.get(str(prueba.fenotipo or "").strip().upper(), "O+")
        prueba.save(update_fields=[*hema_fields, "fenotipo"])


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_transfusion_servicio_ml'),
    ]

    operations = [
        migrations.RunPython(normalize_laboratory_choices, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pruebapretransfusionalpac',
            name='alfa',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pruebapretransfusionalpac',
            name='beta',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pruebapretransfusionalpac',
            name='control_rhesus',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pruebapretransfusionalpac',
            name='coombs_directo',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pruebapretransfusionalpac',
            name='fenotipo',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='pruebapretransfusionalpac',
            name='o',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pruebaspretransfhema',
            name='albumina',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pruebaspretransfhema',
            name='celula_a',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pruebaspretransfhema',
            name='celula_b',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pruebaspretransfhema',
            name='celula_o',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pruebaspretransfhema',
            name='coombs',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pruebaspretransfhema',
            name='cruzada_mayor',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pruebaspretransfhema',
            name='cruzada_menor',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pruebaspretransfhema',
            name='fenotipo',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='pruebaspretransfhema',
            name='hemolisis',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pruebaspretransfhema',
            name='liss',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pruebaspretransfhema',
            name='salina',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=20),
        ),
    ]
