# Generated by Django 4.2.30 on 2026-05-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0004_alter_pruebapretransfusionalpac_alfa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruebapretransfusionalpac',
            name='anti_a',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pruebapretransfusionalpac',
            name='anti_ab',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pruebapretransfusionalpac',
            name='anti_b',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pruebapretransfusionalpac',
            name='anti_d',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pruebaspretransfhema',
            name='anti_a',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pruebaspretransfhema',
            name='anti_ab',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pruebaspretransfhema',
            name='anti_b',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pruebaspretransfhema',
            name='anti_d',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=20),
        ),
    ]
