# Generated by Django 4.2.30 on 2026-06-12 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_alter_pruebapretransfusionalpac_anti_a_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pruebapretransfusionalpac',
            options={'ordering': ['-fecha_hora', 'id'], 'verbose_name': 'Prueba pretransfusional paciente', 'verbose_name_plural': 'Pruebas pretransfusionales paciente'},
        ),
        migrations.AlterModelOptions(
            name='pruebaspretransfhema',
            options={'ordering': ['-fecha', 'id'], 'verbose_name': 'Prueba pretransfusional hemocomponente', 'verbose_name_plural': 'Pruebas pretransfusionales hemocomponente'},
        ),
    ]
