# Generated by Django 4.2.30 on 2026-05-11 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hemocomponente',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nro_bolsa', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nro_tubuladura', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('SANGRE_TOTAL', 'Sangre total'), ('GLOBULOS_ROJOS', 'Globulos rojos'), ('PLASMA', 'Plasma'), ('PLAQUETAS', 'Plaquetas'), ('CRIOPRECIPITADO', 'Crioprecipitado')], max_length=30)),
                ('grupo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('DESPACHADO', 'Despachado'), ('TRANSFUNDIDO', 'Transfundido'), ('DESCARTADO', 'Descartado'), ('VENCIDO', 'Vencido')], default='DISPONIBLE', max_length=20)),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('devuelto', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hemocomponente',
                'verbose_name_plural': 'Hemocomponentes',
                'ordering': ['fecha_vencimiento', 'nro_bolsa'],
            },
        ),
        migrations.CreateModel(
            name='Trazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evento', models.CharField(choices=[('INGRESO', 'Ingreso'), ('FRACCIONAMIENTO', 'Fraccionamiento'), ('RESERVA', 'Reserva'), ('DESPACHO', 'Despacho'), ('DEVOLUCION', 'Devolucion'), ('DESCARTE', 'Descarte')], max_length=30)),
                ('fecha_hora', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trazabilidades_registradas', to=settings.AUTH_USER_MODEL)),
                ('hemocomponente', models.ForeignKey(db_column='nro_bolsa', on_delete=django.db.models.deletion.CASCADE, related_name='trazabilidades', to='inventario.hemocomponente')),
            ],
            options={
                'verbose_name': 'Trazabilidad',
                'verbose_name_plural': 'Trazabilidades',
                'ordering': ['-fecha_hora', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Descarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_accion', models.CharField(choices=[('DESCARTE', 'Descarte'), ('BAJA', 'Baja'), ('VENCIMIENTO', 'Vencimiento')], max_length=30)),
                ('motivo', models.TextField()),
                ('fecha_hora', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('hemocomponente', models.OneToOneField(db_column='nro_bolsa', on_delete=django.db.models.deletion.PROTECT, related_name='descarte', to='inventario.hemocomponente')),
            ],
            options={
                'verbose_name': 'Descarte',
                'verbose_name_plural': 'Descartes',
                'ordering': ['-fecha_hora', 'id'],
            },
        ),
    ]
