# Generated by Django 4.2.30 on 2026-05-19 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def normalize_descarte_tipo_accion(apps, schema_editor):
    Descarte = apps.get_model('inventario', 'Descarte')
    Descarte.objects.filter(tipo_accion='VENCIMIENTO').update(tipo_accion='DESCARTE')
    Descarte.objects.filter(tipo_accion='BAJA').update(tipo_accion='BAJA_FRACCIONAMIENTO')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descarte',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(normalize_descarte_tipo_accion, noop_reverse),
        migrations.AlterField(
            model_name='descarte',
            name='tipo_accion',
            field=models.CharField(choices=[('DESCARTE', 'Descarte'), ('BAJA_FRACCIONAMIENTO', 'Baja por fraccionamiento'), ('INTERCAMBIO_HOSPITAL', 'Intercambiada con otro hospital'), ('DEVUELTA_BANCO', 'Devuelta al banco de sangre')], max_length=30),
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitales',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='descarte',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='descartes', to='inventario.hospital'),
        ),
    ]
