# Generated by Django 4.2.30 on 2026-05-11 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitacionDonante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('servicio', models.CharField(max_length=120)),
                ('sala_cama', models.CharField(blank=True, max_length=60, null=True)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('codigo_donante', models.CharField(max_length=50, unique=True)),
                ('hora', models.TimeField()),
                ('grupo_factor', models.CharField(max_length=5)),
                ('tipo', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Citacion de donante',
                'verbose_name_plural': 'Citaciones de donantes',
                'ordering': ['-fecha', '-hora', 'codigo_donante'],
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especialidad', models.CharField(max_length=120)),
                ('matricula_profesional', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medicos',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ci', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.PositiveSmallIntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('historia_clinica', models.CharField(max_length=50, unique=True)),
                ('grupo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudTransfusion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nro', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('edad_paciente', models.PositiveSmallIntegerField()),
                ('hto', models.FloatField()),
                ('hb', models.FloatField()),
                ('grupo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('hemocomponente', models.CharField(choices=[('SANGRE_TOTAL', 'Sangre total'), ('GLOBULOS_ROJOS', 'Globulos rojos'), ('PLASMA', 'Plasma'), ('PLAQUETAS', 'Plaquetas'), ('CRIOPRECIPITADO', 'Crioprecipitado')], max_length=30)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('tipo_urgencia', models.CharField(choices=[('RUTINA', 'Rutina'), ('URGENTE', 'Urgente'), ('EMERGENCIA', 'Emergencia')], max_length=20)),
                ('diagnostico', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(db_column='id_medico', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_transfusion', to='admision.medico')),
                ('paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_transfusion', to='admision.paciente')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_recepcionadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de transfusion',
                'verbose_name_plural': 'Solicitudes de transfusion',
                'ordering': ['-fecha', '-hora', 'nro'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('EXENTO', 'Exento'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('es_sus', models.BooleanField(default=True)),
                ('id_transfusion', models.PositiveBigIntegerField(blank=True, null=True)),
                ('citacion', models.ForeignKey(blank=True, db_column='id_citacion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='admision.citaciondonante')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConsentimientoInformado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('servicio', models.CharField(max_length=120)),
                ('nombre_familiar', models.CharField(max_length=100)),
                ('apellido_paterno_familiar', models.CharField(max_length=100)),
                ('apellido_materno_familiar', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=30)),
                ('ci', models.CharField(max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(db_column='nro_solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='admision.solicitudtransfusion')),
            ],
            options={
                'verbose_name': 'Consentimiento informado',
                'verbose_name_plural': 'Consentimientos informados',
                'ordering': ['-fecha', 'solicitud'],
            },
        ),
        migrations.AddField(
            model_name='citaciondonante',
            name='solicitud',
            field=models.ForeignKey(db_column='nro_solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='citaciones_donante', to='admision.solicitudtransfusion'),
        ),
        migrations.AddField(
            model_name='citaciondonante',
            name='user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.PROTECT, related_name='citaciones_donante_recepcionadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
