# Generated by Django 4.2.30 on 2026-05-11 07:40
# Adjusted to preserve the existing id_transfusion column while converting it to FK state.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0002_alter_citaciondonante_created_by_and_more'),
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterField(
                    model_name='pago',
                    name='id_transfusion',
                    field=models.ForeignKey(blank=True, db_column='id_transfusion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='laboratorio.transfusion'),
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='pago',
                    name='id_transfusion',
                ),
                migrations.AddField(
                    model_name='pago',
                    name='transfusion',
                    field=models.ForeignKey(blank=True, db_column='id_transfusion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='laboratorio.transfusion'),
                ),
            ],
        ),
    ]
