# Generated by Django 4.2.30 on 2026-05-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0004_especialidad_medico_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
    ]
