# Generated by Django 4.2.30 on 2026-05-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0008_citacion_servicio_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtransfusion',
            name='fraccionado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudtransfusion',
            name='ml',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
