# Generated by Django 4.2.30 on 2026-05-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0009_solicitudtransfusion_fraccionado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citaciondonante',
            name='tipo',
            field=models.CharField(choices=[('PLASMA_FRESCO_CONGELADO', 'Plasma fresco congelado'), ('CRIOPRECIPITADOS', 'Crioprecipitados'), ('CONCENTRADO_PLAQUETAS', 'Concentrado de plaquetas'), ('PAQUETE_GLOBULAR', 'Paquete globular'), ('CONCENTRADO_HELITROCITO_PLAQUETAS', 'Concentrado de helitrocito y plaquetas por aféresis'), ('GLOBULO_ROJO_LAVADO', 'Globulo rojo lavado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitudtransfusion',
            name='hemocomponente',
            field=models.CharField(choices=[('PLASMA_FRESCO_CONGELADO', 'Plasma fresco congelado'), ('CRIOPRECIPITADOS', 'Crioprecipitados'), ('CONCENTRADO_PLAQUETAS', 'Concentrado de plaquetas'), ('PAQUETE_GLOBULAR', 'Paquete globular'), ('CONCENTRADO_HELITROCITO_PLAQUETAS', 'Concentrado de helitrocito y plaquetas por aféresis'), ('GLOBULO_ROJO_LAVADO', 'Globulo rojo lavado')], max_length=50),
        ),
    ]
