# Generated by Django 4.2.30 on 2026-06-12 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0010_alter_citaciondonante_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudtransfusion',
            name='fraccionado',
        ),
        migrations.RemoveField(
            model_name='solicitudtransfusion',
            name='ml',
        ),
    ]
