# Generated by Django 4.2.30 on 2026-06-12 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0011_remove_solicitudtransfusion_fraccionado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtransfusion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('FINALIZADA', 'Finalizada'), ('ARCHIVADA', 'Archivada')], default='PENDIENTE', max_length=15),
        ),
        migrations.AddField(
            model_name='solicitudtransfusion',
            name='servicio',
            field=models.ForeignKey(blank=True, db_column='id_servicio', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_transfusion', to='admision.servicio'),
        ),
        migrations.AlterField(
            model_name='solicitudtransfusion',
            name='nro',
            field=models.CharField(blank=True, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitudtransfusion',
            name='tipo_urgencia',
            field=models.CharField(choices=[('URGENTE', 'Urgente'), ('EN_EL_DIA', 'En el dia'), ('PROGRAMADA', 'Programada')], max_length=20),
        ),
    ]
